# Generated by Django 2.1.3 on 2018-12-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181127_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='value_bool',
        ),
        migrations.RemoveField(
            model_name='data',
            name='value_dec',
        ),
        migrations.RemoveField(
            model_name='data',
            name='value_int',
        ),
        migrations.AlterField(
            model_name='data',
            name='value_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tags',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ValueTypes'),
        ),
    ]
