# Generated by Django 2.1.3 on 2018-12-01 22:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181130_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value_int', models.IntegerField(blank=True)),
                ('value_dec', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('value_text', models.CharField(blank=True, max_length=100)),
                ('value_bool', models.BooleanField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='tag',
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='tags',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ValueTypes'),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.AddField(
            model_name='iotdata',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Tags'),
        ),
    ]
