# Generated by Django 2.1.3 on 2018-12-02 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181201_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdata',
            name='value_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='value_dec',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='value_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='value_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ValueTypes'),
        ),
    ]
