# Generated by Django 2.1.3 on 2018-12-06 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181201_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ValueTypes'),
        ),
        migrations.AlterField(
            model_name='valuetypes',
            name='type',
            field=models.CharField(choices=[('str', 'Alphanumeric text'), ('float', 'Decimal Number'), ('int', 'Integer'), ('bool', 'Boolean')], max_length=6),
        ),
    ]
