# Generated by Django 2.1.3 on 2018-12-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181205_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='valuetypes',
            options={'verbose_name': 'ValueType', 'verbose_name_plural': 'ValueTypes'},
        ),
        migrations.AlterField(
            model_name='tags',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ValueTypes'),
        ),
        migrations.AlterField(
            model_name='valuetypes',
            name='type',
            field=models.CharField(choices=[('string', 'Alphanumeric text'), ('dec', 'Decimal Number'), ('int', 'Integer'), ('bool', 'Boolean')], max_length=6),
        ),
    ]
