# Generated by Django 2.1.3 on 2019-01-15 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20181228_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ValueTypes'),
        ),
    ]
