# Generated by Django 2.1.3 on 2019-08-31 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20190221_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dewpoint', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_uom', models.CharField(blank=True, max_length=10)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_gust', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_uom', models.CharField(blank=True, max_length=10)),
                ('wind_dir', models.IntegerField(blank=True, null=True)),
                ('dir_uom', models.CharField(blank=True, max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WeatherStation',
                'verbose_name_plural': 'WeatherStations',
            },
        ),
        migrations.AlterField(
            model_name='tags',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ValueTypes'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WeatherStations'),
        ),
    ]
