# Generated by Django 2.2.9 on 2020-07-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190831_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='press_uom',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='weatherstations',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='weatherstations',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ValueTypes'),
        ),
        migrations.AlterField(
            model_name='weatherstations',
            name='identifier',
            field=models.CharField(max_length=30),
        ),
    ]
